packages:
  - apps/*
allowBuilds:
  "@tailwindcss/oxide": true
  better-sqlite3: true
  esbuild: true
  lefthook: true
  msw: true
  sharp: true
  workerd: true

blockExoticSubdeps: true
onlyBuiltDependencies: better-sqlite3
